[pytest]

markers =
    ui: Тесты, проверяющие пользовательский интерфейс (Selenium)
    api: Тесты, проверяющие программный интерфейс (Requests)


addopts = --alluredir=allure-results --strict-markers


testpaths = test


python_files = test_*.py
